- src/main/java/org/apache/maven/plugins/site/deploy/AbstractDeployMojo.java
Detail: https://issues.apache.org/jira/browse/MSITE-812
> [MSITE-812] Missing '/' in log when deploying documentation by site:stage

- pom.xml
- src/main/java/org/apache/maven/plugins/site/deploy/AbstractDeployMojo.java
- src/main/java/org/apache/maven/plugins/site/run/SiteRunMojo.java
- src/test/java/org/apache/maven/plugins/site/deploy/AbstractSiteDeployWebDavTest.java
- src/test/java/org/apache/maven/plugins/site/deploy/AuthAsyncProxyServlet.java
- src/test/java/org/apache/maven/plugins/site/deploy/HttpRequest.java
- src/test/java/org/apache/maven/plugins/site/deploy/SimpleDavServerHandler.java
Hi,  I am hunting down insecure maven dependencies.
This pull requests tries to start discussion about upgrading jetty to a more recent version.
jetty 6.1.25 does include  insecure plugin repositories via its jetty-parent . Found out while I compiled a 3rd party project.
Patch is porting the  jetty code to current jetty fixing that issue.
While doing this I found that there is a inner class of a test used in normal business logic "HttpRequest". I refactored it to business logic. 
Since jetty is Java 1.8, I changed maven enforcer to check for java 1.8 project wise. Since Java 1.6 is falling out of extended support in a month, java 1.7 now unsupported and java 1.8 now being the old LTS I think there is little reason to stick with java 1.6.
> [MSITE-828] Upgrade jetty to recent version. Update to java 1.8 (required for jetty)

- src/site/apt/examples/sitedescriptor.apt
* Add note that links to `creating-content.html#Filtering` for additional details regarding the use of dotted properties.
* Update example reference to fluido skin to latest (1.8), to encourage use of newer skin in the example.
> MSITE-848 Update sitedescriptor.apt

- src/site/apt/index.apt.vm
I'd like to add an automatic detection integration test for any links (<a> tags) without an href.  Would that be something you would support?  It would prevent errors like this occuring in the future, as well as ensure that any blue "hyperlink" text would actually take you somewhere!
> MSITE-847: Corrected link to prerequisite maven version.

- src/site/apt/index.apt.vm
@rfscholte testing a hypothesis about how Github sets commiters
> Only reference current version: created on website

- pom.xml
- src/main/java/org/apache/maven/plugins/site/deploy/AbstractDeployMojo.java
- src/main/java/org/apache/maven/plugins/site/render/AbstractSiteRenderingMojo.java
- src/main/java/org/apache/maven/plugins/site/render/ReportDocumentRenderer.java
> [MSITE-757] remove Maven 2 support

- pom.xml
@michael-o 
exclusion no longer necessary with latest doxias
[INFO] +- org.apache.maven.doxia:doxia-site-renderer:jar:1.9.2:compile
[INFO] |  +- org.apache.maven.doxia:doxia-skin-model:jar:1.9.2:compile
[INFO] |  +- org.codehaus.plexus:plexus-velocity:jar:1.2:compile
[INFO] |  +- org.apache.velocity:velocity:jar:1.7:compile
[INFO] |  |  \- commons-lang:commons-lang:jar:2.4:compile
[INFO] |  +- org.apache.velocity:velocity-tools:jar:2.0:compile
[INFO] |  |  +- commons-beanutils:commons-beanutils:jar:1.7.0:compile
[INFO] |  |  +- commons-digester:commons-digester:jar:1.8:compile
[INFO] |  |  +- commons-chain:commons-chain:jar:1.1:compile
[INFO] |  |  +- dom4j:dom4j:jar:1.1:compile
[INFO] |  |  \- oro:oro:jar:2.0.8:compile
[INFO] |  \- …
> [MSITE-861] remove obsolete dependency

- src/site/apt/examples/sitedescriptor.apt
Example is not good since self-closing tag wont work, so it is changed to correct example. 
See [stackoverflow](https://stackoverflow.com/questions/4531772/can-the-script-tag-not-be-self-closed/4531793) for more info.
> Fix script injection example in docs

- src/it/projects/MSITE-484/pom.xml
- src/it/projects/MSITE-497/pom.xml
- src/it/projects/MSITE-506/pom.xml
- src/it/projects/MSITE-512/parent-usage-test/pom.xml
- src/it/projects/MSITE-665/pom.xml
These test failed on macOS with Java above 8; now they pass with
Java 8, 11 and 15 on macOS.
> [MSITE-871] Upgrade Maven Javadoc Plugin in integration tests

- src/main/java/org/apache/maven/plugins/site/deploy/AbstractDeployMojo.java
- src/main/java/org/apache/maven/plugins/site/deploy/AbstractStagingMojo.java
- src/main/java/org/apache/maven/plugins/site/deploy/SiteStageDeployMojo.java
- src/main/java/org/apache/maven/plugins/site/render/AbstractSiteRenderingMojo.java
Continuation of https://issues.apache.org/jira/browse/MNG-6829
Review requested of @elharo
Use this link to re-run the recipe: https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?organizationId=QXBhY2hlIE1hdmVu
If your pull request is …
> [MNG-6829] Replace StringUtils#isEmpty(String) and #isNotEmpty(String)

- Jenkinsfile
- pom.xml
> Expand and update CI for Maven 3.2.5 and newer

- src/site/apt/index.apt.vm
A link exist on the page to filetemplate : https://maven.apache.org/plugins/maven-site-plugin/index.html
but it was removed in https://github.com/apache/maven-site-plugin/commit/5f81392dadcc6899c17e1c64f6957229514118ff
Kind of typo fixes lazy to do jira for that :D
> plugin webpage: remove obsolete link to template file

- Jenkinsfile
- pom.xml
- src/it/projects/MSITE-609/verify.bsh
- src/it/projects/MSITE-627/pom.xml
- src/it/projects/MSITE-627/src/main/java/org/apache/maven/plugins/it/MyReport.java
- src/it/projects/MSITE-842/project/pom.xml
- src/it/projects/MSITE-842/project/src/main/java/org/apache/maven/plugins/it/MyReport.java
- src/it/projects/full-reporting/pom.xml
- src/it/projects/site-deploy/verify.bsh
- src/test/java/org/apache/maven/plugins/site/deploy/AbstractSiteDeployWebDavTest.java
This closes #187
To make clear that you license your contribution …
> [MSITE-1008] Upgrade to Parent 42 and Maven 3.6.3

- src/site/apt/examples/inheritance-site-distribution-management.apt
- src/site/site.xml
Proposed commit message:
```
[MSITE-1010] Add documentation how site repository inheritance
More information including an example how the site repository configuration is inherited,
when using a parent-pom.
closes #MSITE-1010
```
If your pull request is about ~20 lines of code you …
> [MSITE-1010] Add documentation how site repository inheritance

- src/test/java/org/apache/maven/plugins/site/stubs/SiteMavenProjectStub.java
> Use try with resources to avoid deprecated class

- src/main/java/org/apache/maven/plugins/site/descriptor/EffectiveSiteMojo.java
- src/main/java/org/apache/maven/plugins/site/descriptor/SiteDescriptorArtifactMetadata.java
- src/main/java/org/apache/maven/plugins/site/render/AbstractSiteRenderingMojo.java
- src/main/java/org/apache/maven/plugins/site/render/CategorySummaryDocumentRenderer.java
- src/main/java/org/apache/maven/plugins/site/render/ReportDocumentRenderer.java
- src/main/java/org/apache/maven/plugins/site/render/SiteMojo.java
- src/main/java/org/apache/maven/plugins/site/render/SitemapDocumentRenderer.java
- src/main/java/org/apache/maven/plugins/site/run/DoxiaFilter.java
- src/main/java/org/apache/maven/plugins/site/run/SiteRunMojo.java
- src/test/java/org/apache/maven/plugins/site/stubs/SiteMavenProjectStub.java
> Replace deprecated methods

- src/test/java/org/apache/maven/plugins/site/deploy/AuthAsyncProxyServlet.java
- src/test/java/org/apache/maven/plugins/site/deploy/SimpleDavServerHandler.java
Passing tests should generate no output
@michael-o
> Remove debugging strings from test output

- src/test/java/org/apache/maven/plugins/site/deploy/AbstractSiteDeployWebDavTest.java
> [MSITE-945] More modern temporary file handling

- src/site/apt/history.apt
- src/site/fml/faq.fml
Trivial changes in the documentation.
@michael-o hopefully everything works now.
> Fix typos in history.apt and faq.fml

- pom.xml
it is managed automatically
(cherry picked from commit ac1f4c83a11da304144ab1a9314c05afd65256c0)
> Drop additional configuration for requirementsHistories

- src/site/apt/examples/sitedescriptor.apt
see https://github.com/apache/maven-site/issues/660#issuecomment-2669720009
> [MSITE-1035] use jquery as example js in site descriptor
