- src/site/apt/index.apt.vm
@rfscholte created on local workstation
> remove info about old version

- pom.xml
@hboutemy this is far as I could easily push maven-plugin-testing-harness. Going past 2.1 will require some more work.
> update test dependencies

- .gitignore
> add .checkstyle to .gitignore

- src/main/java/org/apache/maven/plugins/site/run/SiteRunMojo.java
- src/test/java/org/apache/maven/plugins/site/deploy/AuthAsyncProxyServlet.java
- src/test/java/org/apache/maven/plugins/site/deploy/SimpleDavServerHandler.java
- src/test/java/org/apache/maven/plugins/site/stubs/SiteMavenProjectStub.java
> remove unused code

- pom.xml
> [MSITE-859] update apache commons lang and IO

- src/site/apt/examples/adding-deploy-protocol.apt.vm
> [MSITE-757] drop Maven 2 mention

- README.md
Very trivial change to verify that the CI really is busted
> trivial change

- .github/workflows/maven-verify.yml
> [MSITE-877] Shared GitHub Actions

- pom.xml
- src/it/projects/MSITE-504/maven-plugin/pom.xml
- src/it/projects/MSITE-548/root/pom.xml
- src/it/projects/inheritance-interpolation/repo-parent/pom.xml
- src/it/projects/site-sd-top-parent-no-site/root/pom.xml
> [MSITE-906] Upgrade plugins and components 

- src/site/apt/examples/sitedescriptor.apt
> Remove reference to limits of old beta versions

- src/main/java/org/apache/maven/plugins/site/render/AbstractSiteRenderingMojo.java
The performance of the empty array version is the same, and sometimes even better, compared
to the pre-sized version. Also, passing a pre-sized array is dangerous for a concurrent or
synchronized collection as a data race is possible between the <code>size</code> and <code>toArray</code>
calls. This may result in extra <code>null</code>s at the end of the array if the collection was concurrently
shrunk during the operation.</p>
See https://shipilev.net/blog/2016/arrays-wisdom-ancients/ for more details.
* ToArrayCallWithZeroLengthArrayArgument (1)
require a JIRA issue.  Your pull request should address just this …
> refactor: refactor bad smell ToArrayCallWithZeroLengthArrayArgument

- src/main/java/org/apache/maven/plugins/site/render/SiteMap.java
> Sitemap fixes

- src/site/apt/usage.apt
> Remove old URLs and Maven versions

- pom.xml
We need to separate the Fluido Skin version used for the ITs and dev profile from the site generation which depends on the parent POM config. Both can be incompatible.
This closes #148
[Individual Contributor …
> [MSITE-960] +[MSITE-961]

- src/it/projects/MSITE-497/apps/app/pom.xml
- src/it/projects/MSITE-497/apps/app/src/main/java/org/apache/maven/App.java
- src/it/projects/MSITE-506/pom.xml
- src/it/projects/MSITE-506/src/test/java/mavenjavadoc/AppTest.java
- src/it/projects/MSITE-665/pom.xml
- src/it/projects/failure/pom.xml
- src/it/projects/full-reporting/pom.xml
- src/it/projects/full-reporting/verify.groovy
- src/it/projects/it-plugin-test/pom.xml
- src/it/projects/new-configuration/pom.xml
- src/it/projects/no-version/pom.xml
- src/it/projects/surefire-report/pom.xml
> Update log4j and junit to avoid security reports in ITs

- src/main/java/org/apache/maven/plugins/site/render/ReportDocumentRenderer.java
- src/test/java/org/apache/maven/plugins/site/deploy/AbstractSiteDeployWebDavTest.java
- src/test/java/org/apache/maven/plugins/site/deploy/AuthAsyncProxyServlet.java
- src/test/java/org/apache/maven/plugins/site/deploy/HttpRequest.java
- src/test/java/org/apache/maven/plugins/site/deploy/SimpleDavServerHandler.java
As discussed on
- https://github.com/apache/maven-scm/pull/184
- https://issues.apache.org/jira/browse/MNG-6847
Review requested of @elharo
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.UseDiamondOperator?organizationId=QXBhY2hlIE1hdmVu
---
be performed on your pull request …
> [MNG-6847] Use diamond operator

- src/main/java/org/apache/maven/plugins/site/render/AbstractSiteRenderingMojo.java
This closes #162
To make clear that you license your contribution …
> [MSITE-987] Consistently log when skipping report goal execution

- src/it/mrm/settings.xml
- src/it/projects/MSITE-604/parent/pom.xml
- src/it/projects/MSITE-604/pom.xml
- src/it/projects/MSITE-604/verify.groovy
- src/it/projects/inheritance-interpolation/repo-parent/pom.xml
- src/main/java/org/apache/maven/plugins/site/deploy/SiteStageDeployMojo.java
This closes #195
To make clear that you license your contribution …
> [MSITE-1012] Clean up notion that sites aren't deployed to repositories

- src/test/java/org/apache/maven/plugins/site/deploy/AbstractSiteDeployWebDavTest.java
Also cures another deprecation warning
@michael-o
> Use charset in test

- src/main/java/org/apache/maven/plugins/site/descriptor/SiteDescriptorArtifactMetadata.java
> Earlier detection of mkdirs failure

- src/site/xdoc/download.xml.vm
JIRA issue: [MSITE-986](https://issues.apache.org/jira/browse/MSITE-986)
please ask on the developers …
> [MSITE-986] - Refresh download page

- src/site/xdoc/download.xml.vm
(cherry picked from commit 12c8a9d89a6a4865e1c94c766f715131ee6f5eb5)
> [MSITE-986] Refresh download page

- pom.xml
> Drop additional configuration for requirementsHistories

- .github/workflows/release-drafter.yml
> Allow to manually execute release drafter
